## CHANGE this to the name of your plugin.
name: AlternateBackpackRecipeAddon

## CHANGE this to your username.
author: Antitonius

## CHANGE this to a meaninful but short description of your plugin.
description: A Slimefun4 Addon that is adding an alternative recipe for Slimefun backpacks.

## CHANGE this to the path of the class that extends JavaPlugin.
main: com.unipi.alexandris.slimefunaddon.altbackpackrecipe.AltBackpackRecipeAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://anthonyal.github.io

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
commands:
  altbackpack:
    description: The command group for altbackpack recipe.
    aliases: abr
    permission: altbackpack
  permissions:
    altbackpack:
      description: Access to all altbackpack commands.
      default: op